"""empty message

Revision ID: 13019692b99d
Revises: 7caa094f3ce6
Create Date: 2024-08-28 22:44:47.310323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13019692b99d'
down_revision = '7caa094f3ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
