"""empty message

Revision ID: 1daf0d91f65f
Revises: 44a23660661d
Create Date: 2024-09-16 22:40:05.447933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1daf0d91f65f'
down_revision = '44a23660661d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.drop_constraint('user_image_image_url_key', type_='unique')
        batch_op.drop_constraint('user_image_public_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_image_public_id_key', ['public_id'])
        batch_op.create_unique_constraint('user_image_image_url_key', ['image_url'])

    # ### end Alembic commands ###
