"""empty message

Revision ID: 224f81f0be75
Revises: 42ef61050df9
Create Date: 2024-09-09 02:40:10.133740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224f81f0be75'
down_revision = '42ef61050df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('title', 'owner_id', name='unique_img_title_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    # ### end Alembic commands ###
