"""empty message

Revision ID: 284492a30b3f
Revises: fadf5c6db6ab
Create Date: 2024-09-10 20:02:41.464590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284492a30b3f'
down_revision = 'fadf5c6db6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer_review', schema=None) as batch_op:
        batch_op.alter_column('brewery_review_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brewery_name', sa.String(), nullable=False))
        batch_op.drop_column('brewer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brewer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('brewery_name')

    with op.batch_alter_table('beer_review', schema=None) as batch_op:
        batch_op.alter_column('brewery_review_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
