"""empty message

Revision ID: 403b9217caba
Revises: b339773005c4
Create Date: 2024-09-20 00:47:17.523335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403b9217caba'
down_revision = 'b339773005c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.alter_column('brewery_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.alter_column('brewery_id',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
