"""empty message

Revision ID: 51800f89f283
Revises: f4b3eeb86073
Create Date: 2024-09-16 03:33:19.720019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51800f89f283'
down_revision = 'f4b3eeb86073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
