"""empty message

Revision ID: 5935ff413045
Revises: 1daf0d91f65f
Create Date: 2024-09-19 00:44:29.851691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5935ff413045'
down_revision = '1daf0d91f65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('reward_name', sa.String(length=250), nullable=True),
    sa.Column('reward_value', sa.Integer(), nullable=True),
    sa.Column('reward_type', sa.String(length=250), nullable=True),
    sa.Column('point_cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rewards')
    # ### end Alembic commands ###
