"""empty message

Revision ID: 595a9581d9b1
Revises: 932d4e8b524c
Create Date: 2024-09-20 22:16:24.218707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595a9581d9b1'
down_revision = '932d4e8b524c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
