"""empty message

Revision ID: 5b3fdfee7572
Revises: e5cfaadc8d82
Create Date: 2024-08-26 23:16:12.161822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3fdfee7572'
down_revision = 'e5cfaadc8d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
