"""empty message

Revision ID: 7caa094f3ce6
Revises: 2f2179a2f6e3
Create Date: 2024-08-27 00:45:31.445427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caa094f3ce6'
down_revision = '2f2179a2f6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=250), nullable=False))
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('action')

    # ### end Alembic commands ###
