"""empty message

Revision ID: 9935090a1ccc
Revises: fb97dc6f6605
Create Date: 2024-08-22 00:14:21.624640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9935090a1ccc'
down_revision = 'fb97dc6f6605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_beers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorited_beer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_beers_led_favorite_beers_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_beers_led_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'beer', ['favorited_beer_id'], ['id'])
        batch_op.drop_column('led_favorite_beers')
        batch_op.drop_column('led_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_beers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('led_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('led_favorite_beers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_beers_led_user_id_fkey', 'user', ['led_user_id'], ['id'])
        batch_op.create_foreign_key('favorite_beers_led_favorite_beers_fkey', 'beer', ['led_favorite_beers'], ['id'])
        batch_op.drop_column('favorited_beer_id')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
