"""empty message

Revision ID: b339773005c4
Revises: 9432e1fde488
Create Date: 2024-09-20 00:32:48.156568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b339773005c4'
down_revision = '9432e1fde488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brewery_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.drop_column('brewery_id')

    # ### end Alembic commands ###
