"""empty message

Revision ID: c87aa87985f0
Revises: e6fcacc1c788
Create Date: 2024-09-23 04:13:29.921389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87aa87985f0'
down_revision = 'e6fcacc1c788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery_review', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
