"""empty message

Revision ID: e1ff09d4d8aa
Revises: 702061ffc5a0
Create Date: 2024-09-24 00:00:16.893738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ff09d4d8aa'
down_revision = '702061ffc5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.drop_constraint('unique_profile_image_per_user', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_profile_image_per_user', ['owner_id', 'is_profile_image'])

    # ### end Alembic commands ###
