"""empty message

Revision ID: e5cfaadc8d82
Revises: 75787a03be0f
Create Date: 2024-08-26 23:11:20.939183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cfaadc8d82'
down_revision = '75787a03be0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brewery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brewery_name', sa.String(length=250), nullable=True),
    sa.Column('brewery_type', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('state_province', sa.String(length=250), nullable=True),
    sa.Column('longitude', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=250), nullable=True),
    sa.Column('website_url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_breweries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('favorited_brewery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorited_brewery_id'], ['brewery.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_breweries')
    op.drop_table('brewery')
    # ### end Alembic commands ###
