"""empty message

Revision ID: fb97dc6f6605
Revises: 4f4cf9e55d35
Create Date: 2024-08-21 23:55:55.429821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb97dc6f6605'
down_revision = '4f4cf9e55d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beer_name', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('flavor', sa.String(length=250), nullable=True),
    sa.Column('ABV', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_beers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('led_user_id', sa.Integer(), nullable=True),
    sa.Column('led_favorite_beers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['led_favorite_beers'], ['beer.id'], ),
    sa.ForeignKeyConstraint(['led_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('favorited_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorited_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_users')
    op.drop_table('favorite_beers')
    op.drop_table('beer')
    # ### end Alembic commands ###
